name        : font-adobe-75dpi
version     : 1.0.3
release     : 2
source      :
    - http://xorg.freedesktop.org/releases/individual/font/font-adobe-75dpi-1.0.3.tar.bz2 : c6024a1e4a1e65f413f994dd08b734efd393ce0a502eb465deb77b9a36db4d09
license     :
    - MIT
component   : xorg.fonts
summary     : |
    X.Org fonts: font-adobe-75dpi
description : |
    X.Org fonts: font-adobe-75dpi
builddeps  :
    - pkgconfig(fontutil)
    - bdftopcf
    - mkfontdir
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
