name       : font-adobe-75dpi
version    : 1.0.4
release    : 5
source     :
    - https://www.x.org/releases/individual/font/font-adobe-75dpi-1.0.4.tar.gz : 6a2be7148406fc5df4f1b5258955418fdacb17ee19946613164517ff501c41c7
license    :
    - MIT
component  : xorg.fonts
summary    : |
    X.Org fonts: font-adobe-75dpi
description: |
    X.Org fonts: font-adobe-75dpi
builddeps  :
    - pkgconfig(fontutil)
    - pkgconfig(harfbuzz-icu)
    - bdftopcf
    - mkfontscale
setup      : |
    %configure --with-fontrootdir=/usr/share/fonts
build      : |
    %make
install    : |
    %make_install
